---
all:
  children:
    home:
      hosts:
        homeprod:
        pisrv:
        hydrogen:
        phosphorus:
    mdp:
      hosts:
        magnesium:
        nitrogen:
        sodium:
    laptop:
      hosts:
        neon: