---
all:
  children:
#    home:
#      hosts:
#        homeprod:
        beryllium:
#          ansible_host: "192.168.1.104"
          ansible_host: "beryllium"
          ansible_user: "jul"
        hydrogen:
#          ansible_host: "192.168.1.249"
          ansible_host: "hydrogen"
          ansible_user: "jul"
#        phosphorus:
    mdp:
      hosts:
#        magnesium:
        nitrogen:
#          ansible_host: "192.168.1.246"
          ansible_host: "nitrogen"
          ansible_user: "jul"
        sodium:
#          ansible_host: "192.168.1.254"
          ansible_host: "sodium"
          ansible_user: "mdp"
#          ansible_python_interpreter: "/usr/bin/python3"
#    laptop:
#      hosts:
#        neon: