---
all:
  children:
    cloud:
      hosts:
        uodev2:
    home:
      hosts:
        homeprod:
        pisrv:
        dietdev:
        hydrogen:
    workstation:
      hosts:
        neon:
        beelink:
        hpdev:
        zorin:
    server:
      children:
        cloud:
        home:
