---
all:
  children:
#    home:
#      hosts:
#        homeprod:
#        pisrv:
#        hydrogen:
#        phosphorus:
    mdp:
      hosts:
#        magnesium:
        nitrogen:
#          ansible_host: "192.168.1.246"
          ansible_host: "nitrogen"
          ansible_user: "dietpi"
        sodium:
          ansible_host: "192.168.1.254"
#          ansible_host: "sodium"
          ansible_user: "mdp"
#          ansible_python_interpreter: "/usr/bin/python3"
#    server:
#      hosts:
#        neon: