---
- hosts: all
  become: true

  pre_tasks:
    - name: Install updates
      tags: always
      apt:
        update_cache: true
        upgrade: dist
      changed_when: false

  tasks:
    - name: Set timezone
      tags: settings,time,bootstrap
      community.general.timezone:
        name: "Europe/Paris"

    - name: Grant user sudo privileges without password
      lineinfile:
        path: "/etc/sudoers.d/{{ ansible_user }}"
        line: "{{ ansible_user }} ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: true
        validate: "visudo -cf %s"

    - name: Bash configuration
      ansible.builtin.include_tasks:
        file: tasks/bash_config.yml

- hosts: server
  become: true
  tasks:
    - name: Install and configure ufw
      ansible.builtin.include_tasks:
        file: tasks/ufw.yml

- hosts: all
  become: true
  post_tasks:
    - name: cleanup package cache
      tags: always
      apt:
        autoclean: true
      changed_when: false

    - name: autoremove orphan packages
      tags: always
      apt:
        autoremove: true
        purge: true
