---
- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Install updates
      apt:
        update_cache: yes
        upgrade: dist
      changed_when: False

  tasks:
    - name: Grant jul sudo privileges without password
      lineinfile:
        path: /etc/sudoer.d/jul
        line: "jul ALL=(ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: true
        validate: "visudo -cf %s"

    - name: Copy function upg
      copy:
        src: files/upg.sh
        dest: /usr/local/bin/upg
        owner: jul
        group: jul
        mode: 0770

    - import_playbook: tasks/bash_config.yml

    - import_playbook: tasks/packages.yml
