- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Install updates
      tags: always
      apt:
        update_cache: yes
        upgrade: dist
      changed_when: False

  tasks:
    - name: Copy sudoer_jul
      copy:
        src: files/sudoer_jul
        dest: /etc/sudoers.d/jul
        owner: root
        group: root
        mode: 0440

    - name: Copy function upg
      copy:
        src: files/upg.sh
        dest: /usr/local/bin/upg
        owner: jul
        group: jul
        mode: 0770

    - include: tasks/bash_config.yml

    - include: tasks/packages.yml
