---
- hosts: mdp
  become: true
#  pre_tasks:
#    - name: apt | install updates
#      ansible.builtin.apt:
#        update_cache: true
#        upgrade: dist

  tasks:
    - ansible.builtin.import_tasks:
        file: "tasks/debug.yml"

#  post_tasks:
#    - name: apt | cleanup package cache
#      ansible.builtin.apt:
#        autoclean: true

#    - name: apt | remove orphan packages
#      ansible.builtin.apt:
#        autoremove: true
#        purge: true