---
- hosts: dietdev
  become: true

  tasks:
    - name: grant user sudo privileges without password
      ansible.builtin.lineinfile:
        path: "/etc/sudoers.d/{{ansible_user}}"
        line: "{{ansible_user}} ALL=(ALL:ALL) NOPASSWD: ALL"
        state: present
        mode: 0440
        create: true
        validate: "visudo -cf %s"
