---
- hosts: homeprod
  become: true

  pre_tasks:
    - name: Install updates
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist

  tasks:
    - name: syncthing-controlled directories
      ansible.builtin.include_tasks:
        file: tasks/syncthing_dir.yml
      when: syncthing is defined and syncthing == true
