---
- name: Create .bash config directory
  file:
    path: "/home/{{ ansible_user }}/.bash"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0700

- name: Add bash config files
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ ansible_user }}/{{ item.dest }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0600
  with_items:
    - { src: 'bashrc', dest: '.bashrc'}
    - { src: 'bash_aliases', dest: '.bash/bash_aliases' }
    - { src: 'bash_prompt', dest: '.bash/bash_prompt' }

