---
- name: Install packages
  apt:
    name:
      - bat
      - duf
      - exa
      - fail2ban
      - htop
      - ncdu
      - neofetch
      - rsync
      - samba
    state: latest
    update_cache: true

