---
- name: Install packages
  ansible.builtin.apt:
    name:
      - bat
      - fail2ban
      - htop
      - ncdu
      - neofetch
      - rsync
    state: latest
    update_cache: true

- name: Install duf
  ansible.builtin.apt:
    name: duf
  when: duf is defined and duf == true

- name: Install exa
  ansible.builtin.apt:
    name: exa
  when: exa is defined and exa == true
