---
- name: Sublime | Add gpg key and repo
  block:
    - name: Sublime | Add gpg key
      ansible.builtin.get_url:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        # Use .asc extension to avoid gpg --dearmor step
        dest: /etc/apt/trusted.gpg.d/sublimehq-archive.asc

    - name: Sublime | Add repo
      ansible.builtin.apt_repository:
        repo: "deb https://download.sublimetext.com/ apt/stable/"
        state: present
        filename: sublime-text

- name: Nala | Add gpg key and repo
  block:
    - name: Nala | Add gpg key
      ansible.builtin.get_url:
        url: https://deb.volian.org/volian/scar.key
        dest: /etc/apt/trusted.gpg.d/volian-archive-scar-unstable.gpg

    - name: Nala | Add repo
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64,arm64,armhf] http://deb.volian.org/volian/ scar main"
        state: present
        filename: volian-archive-scar-unstable

- name: Syncthing | Add gpg key and repo
  block:
    - name: Syncthing | Add gpg key
      ansible.builtin.get_url:
        url: https://syncthing.net/release-key.gpg
        dest: /usr/share/keyrings/syncthing-archive-keyring.gpg

    - name: Syncthing | Add repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
        state: present
        filename: syncthing

    - name: Syncthing | Set repo priority
      ansible.builtin.blockinfile:
        path: "/etc/apt/preferences.d/syncthing"
        state: present
        create: true
        block: |
          Package: *
          Pin: origin apt.syncthing.net
          Pin-Priority: 990
