---
# adding syncthing repository for debian and ubuntu
- name: syncthing | add repository for debian and ubuntu
  block:
    - name: syncthing | add gpg key
      ansible.builtin.get_url:
        url: "https://syncthing.net/release-key.gpg"
        dest: "/usr/share/keyrings/syncthing-archive-keyring.gpg"

    - name: syncthing | add repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
        state: present
        filename: syncthing

    - name: syncthing | set repository priority
      ansible.builtin.blockinfile:
        path: "/etc/apt/preferences.d/syncthing"
        state: present
        create: true
        block: |
          Package: *
          Pin: origin apt.syncthing.net
          Pin-Priority: 990
  when:
    - ansible_distribution in ["Debian", "Pop!_OS", "Ubuntu"]
    - syncthing is defined
    - syncthing == true

- name: syncthing | install the packages
  ansible.builtin.apt:
    update_cache: true
    name: syncthing
    state: latest
  register: syncthing_installed
  when: syncthing is defined and syncthing == true

# Enable and start syncthing
# Note: Not using systemd module because it triggers a dbus error due to no session while user is not logged in
- name: syncthing | start and enable service
  ansible.builtin.command: "{{ item }}"
  with_items:
    - "systemctl enable syncthing@{{ ansible_user }}"
    - "systemctl restart syncthing@{{ ansible_user }}"
  when: syncthing_installed.changed

- name: syncthing | pause to ensure config file exists
  become_user: "{{ ansible_user }}"
  wait_for:
    path: "/home/{{ ansible_user }}/.config/syncthing/config.xml"
    delay: 10
  when: syncthing_installed.changed

- name: syncthing | modify configuration file
  become_user: "{{ ansible_user }}"
  replace:
    path: "/home/{{ ansible_user }}/.config/syncthing/config.xml"
    regexp: "{{ item.before }}"
    replace: "{{ item.after }}"
  with_items:
    - {before: "<theme>default</theme>", after: "<theme>dark</theme>"}
    - {before: "<address>127.0.0.1:8384</address>", after: "<address>0.0.0.0:8384</address>"}
  register: syncthing_config
  when: syncthing is defined and syncthing == true

- name: syncthing | restart syncthing
  ansible.builtin.command: "systemctl restart syncthing@{{ ansible_user }}"
  when: syncthing_config.changed

- name: syncthing | remove default sync directory (~/Sync)
  ansible.builtin.file:
    path: "/home/{{ ansible_user }}/Sync"
    state: absent
  when: syncthing is defined and syncthing == true
