---
# add syncthing-controlled directories
- name: syncthing | add syncthing-controlled directories
  block:
    - name: syncthing | create directories
      ansible.builtin.file:
        path: "/syncthing/{{ item.dir }}"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0700
      with_items:
        - {dir: 'smartphone/audiobooks'}
        - {dir: 'smartphone/documents'}
        - {dir: 'smartphone/music'}
        - {dir: 'smartphone/photos'}
        - {dir: 'smartphone/videos'}
        - {dir: 'workstation/bin'}
        - {dir: 'workstation/calibre'}
        - {dir: 'workstation/documents/associatif'}
        - {dir: 'workstation/documents/personnel'}
        - {dir: 'workstation/documents/professionnel'}
        - {dir: 'workstation/downloads'}
        - {dir: 'workstation/images'}
        - {dir: 'workstation/music'}
        - {dir: 'workstation/scan/personnel'}
        - {dir: 'workstation/scan/professionnel'}
        - {dir: 'workstation/videos'}

    - name: syncthing | copy .stignore file to synced directories
      ansible.builtin.copy:
        src: stignore
        dest: "/syncthing/{{ item.dir }}/.stignore"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0600
      with_items:
        - {dir: 'smartphone/audiobooks'}
        - {dir: 'smartphone/documents'}
        - {dir: 'smartphone/music'}
        - {dir: 'smartphone/photos'}
        - {dir: 'smartphone/videos'}
        - {dir: 'workstation/bin'}
        - {dir: 'workstation/calibre'}
        - {dir: 'workstation/documents/associatif'}
        - {dir: 'workstation/documents/personnel'}
        - {dir: 'workstation/documents/professionnel'}
        - {dir: 'workstation/downloads'}
        - {dir: 'workstation/images'}
        - {dir: 'workstation/music'}
        - {dir: 'workstation/scan/personnel'}
        - {dir: 'workstation/scan/professionnel'}
        - {dir: 'workstation/videos'}
  when: syncthing is defined and syncthing == true
