---
- name: ufw | install the packages
  ansible.builtin.apt:
    name: ufw
    state: latest
    update_cache: true

- name: ufw | reset existing rules
  community.general.ufw:
    state: reset

- name: set logging level
  community.general.ufw:
    logging: "low"

- name: ufw | set default outgoing policy
  community.general.ufw:
    default: allow
    direction: outgoing

- name: ufw | set default incoming policy
  community.general.ufw:
    default: deny
    direction: incoming

- name: ufw | allow ssh connections
  community.general.ufw:
    rule: allow
    port: "22"
    proto: any
    log: true

- name: ufw | allow http connections
  community.general.ufw:
    rule: allow
    port: "80"
    proto: any
  when: http is defined and http == true

- name: ufw | set rules for samba
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - {port: "137", proto: "udp"}
    - {port: "138", proto: "udp"}
    - {port: "139", proto: "tcp"}
    - {port: "445", proto: "udp"}
  when: samba is defined and samba == true

- name: ufw | set rules for syncthing
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - {port: "22000", proto: "tcp"}
    - {port: "22000", proto: "udp"}
    - {port: "21027", proto: "udp"}
    - {port: "8384", proto: "tcp"}
  when: syncthing is defined and syncthing == true

- name: ufw | allow connection to dietpi dashboard
  community.general.ufw:
    rule: allow
    port: "5252"
    proto: "tcp"
  when: dietdash is defined and dietdash == true

- name: ufw | reload and enable service
  community.general.ufw:
    state: enabled
