---
- name: Install ufw package
  apt:
    name: ufw
    state: latest
    update_cache: true

- name: Reset existing rules if some exist
  community.general.ufw:
    state: reset

- name: Set logging
  community.general.ufw:
    logging: "on"

- name: Set default outgoing policy
  community.general.ufw:
    default: allow
    direction: outgoing

- name: Set default incoming policy
  community.general.ufw:
    default: deny
    direction: incoming

- name: Allow ssh connections
  community.general.ufw:
    rule: allow
    port: "22"
    proto: any

- name: Allow http connections
  community.general.ufw:
    rule: allow
    port: "80"
    proto: any

- name: Set Samba rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - {port: "137", proto: "udp"}
    - {port: "138", proto: "udp"}
    - {port: "139", proto: "tcp"}
    - {port: "445", proto: "udp"}

- name: Set Syncthing rules
  community.general.ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - {port: "22000", proto: "tcp"}
    - {port: "22000", proto: "udp"}
    - {port: "21027", proto: "udp"}
    - {port: "8384", proto: "tcp"}
