---
- name: unattended upgrades | install package
  ansible.builtin.apt:
    state: latest
    name: unattended-upgrades
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: unattended upgrades | copy 20auto-upgrades file
  ansible.builtin.copy:
    src: 20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution in ['Debian', 'Ubuntu']

- name: unattended upgrades | copy 50unattended-upgrades file (debian)
  ansible.builtin.copy:
    src: 50unattended-upgrades_debian
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Debian"

- name: unattended upgrades | copy 50unattended-upgrades file (ubuntu)
  ansible.builtin.copy:
    src: 50unattended-upgrades_ubuntu
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == "Ubuntu"

- name: unattended-upgrades | start and enable the service
  ansible.builtin.service:
    name: unattended-upgrades
    state: started
    enabled: true
