---
- name: loop examples users
  hosts: localhost
  gather_facts: false
  vars:
    users:
      main:
        name: "jul"
        password: "test"
      ansible:
        name: "otto"
#        password: ""
      guest:
        name: "invite"
        password: "guest_user"

  tasks:
  - name: loop through users using map to create a list of names
    ansible.builtin.debug:
      msg: "username : {{ item }}"
    loop: "{{ users | dict2items | map(attribute='value.name') }}"

  - name: loop through users using map to create a list of passwords
    ansible.builtin.debug:
      msg: "password : {{ item }}"
    loop: "{{ users | dict2items | selectattr('value.password','defined') | map(attribute='value.password') }}"

  - name: show the name of the main user
    ansible.builtin.debug:
      msg: "username : {{ users.main.name }}"
