---
- name: loop examples
  hosts: localhost
  gather_facts: false
  vars:
    open_ports:
      - port: 80
        protocol: "tcp"
      - port: 8080
        protocol: "tcp"
      - port: 3000
        protocol: "tcp"

  tasks:
  - name: loop through the ports to be opened
    ansible.builtin.debug:
      msg: "Port: {{ item.port }} with protocol {{ item.protocol }}"
    loop: "{{ open_ports }}"
